language: python 
sudo: false

python:
        - "3.4"
        - "3.3"
        - "2.7"
        - "2.6"

before_install:
        - pip uninstall argparse
        - pip freeze

install:
        - "pip install -r requirements-${TRAVIS_PYTHON_VERSION}.txt"

before_script:
        - python setup.py build_sphinx install

script:
        - pep8 git_guilt
        - "[[ ${TRAVIS_PYTHON_VERSION} == 2.6 ]] || pylint git_guilt"
        - nosetests test/test_guilt.py --with-coverage --cover-package=git_guilt
        - nosetests test/test_integration.py
        - git guilt HEAD~1 HEAD
        - cd git_test_repo
        - git guilt HEAD~3 HEAD

after_success:
        - cd ${TRAVIS_BUILD_DIR}
        - coveralls
