language: python

python:
        - "2.7"
        - "3.2"

install:
        - "pip install -r requirements.txt"

script:
        - pylint src/*
        - nosetests test/ --with-coverage --cover-package=guilt

after_success:
        coveralls
