language: python 
sudo: false

python:
        - "3.5"
        - "2.7"

before_install:
        - pip install -r build_requirements.txt
        - pip freeze

script:
        - tox

after_success:
        - cd ${TRAVIS_BUILD_DIR}
        - coveralls
        - git guilt HEAD~1 HEAD
