language: python

sudo: false

python:
        - "3.4"
        - "3.3"
        - "2.7"
        - "2.6"

install:
        - "pip install -r requirements-${TRAVIS_PYTHON_VERSION}.txt"

script:
        - pep8 src
        - pylint src/*.py
        - nosetests test/test_guilt.py --with-coverage --cover-package=guilt
        - pip install .
        - nosetests test/test_integration.py
        - cd git_test_repo
        - python ../src/guilt.py HEAD~3 HEAD

after_success:
        coveralls
