language: python 
sudo: false

python:
        - "3.5"

before_script:
        - pip freeze

script:
        - tox -vv

after_success:
        - cd ${TRAVIS_BUILD_DIR}
        - coveralls
        - git guilt HEAD~1 HEAD
