language: python

sudo: false

python:
        - "3.4"
        - "3.3"

install:
        - "pip install -r requirements.txt"

script:
        - pep8 src
        - nosetests test/ --with-coverage --cover-package=guilt
        - pylint src/*.py

after_success:
        coveralls
